FROM rayruan/ubt1804_x86_64:basic

ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 80 21

#    && basicPkgs='vim htop tree dnsutils zip sed cvs subversion make gcc g++ autoconf automake curl' \

# change the /etc/apt/source.list
RUN cat>>/etc/apt/sources.list<<EOF \
deb-src http://archive.ubuntu.com/ubuntu bionic main restricted #Added by software-properties
deb http://mirrors.aliyun.com/ubuntu/ bionic main restricted
deb-src http://mirrors.aliyun.com/ubuntu/ bionic universe multiverse main restricted #Added by software-properties
deb http://mirrors.aliyun.com/ubuntu/ bionic-updates main restricted
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-updates universe multiverse main restricted #Added by software-properties
deb http://mirrors.aliyun.com/ubuntu/ bionic universe
deb http://mirrors.aliyun.com/ubuntu/ bionic-updates universe
deb http://mirrors.aliyun.com/ubuntu/ bionic multiverse
deb http://mirrors.aliyun.com/ubuntu/ bionic-updates multiverse
deb http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-backports main restricted universe multiverse #Added by software-properties
deb http://mirrors.aliyun.com/ubuntu/ bionic-security main restricted
deb-src http://mirrors.aliyun.com/ubuntu/ bionic-security universe multiverse main restricted #Added by software-properties
deb http://mirrors.aliyun.com/ubuntu/ bionic-security universe
deb http://mirrors.aliyun.com/ubuntu/ bionic-security multiverse
deb [arch=amd64] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu bionic stable
deb http://security.ubuntu.com/ubuntu xenial-security main
deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
deb http://us.archive.ubuntu.com/ubuntu/ bionic universe
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates universe
deb http://us.archive.ubuntu.com/ubuntu/ bionic multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu bionic-security main restricted
deb http://security.ubuntu.com/ubuntu bionic-security universe
deb http://security.ubuntu.com/ubuntu bionic-security multiverse
EOF

RUN apt-get update \
    && apt-get -y dist-upgrade \
    && apt-get -y upgrade \
    && basicPkgs='vim htop tree dnsutils zip sed cvs subversion make gcc g++ autoconf automake curl python2.7 python-dev python-pysqlite2 python-minimal python3-dev python3-pip python3-sphinx libfreetype6-dev libjpeg8-dev texlive-fonts-recommended texlive-latex-extra zlib1g-dev fonts-liberation cpio libgl1-mesa-dev libglu1-mesa-dev xterm tmux libncurses5-dev libncursesw5-dev libssl-dev bison libbison-dev bc lzop zip libgtk-3-dev graphviz' \
    && dependPkgs='gawk wget git diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev'\
    && apt-get -y install $dependPkgs $basicPkgs

#RUN apt-get -y install coreutils texi2html mercurial asciidoc groff 
#help2man 
#docbook-utils desktop-file-utils 
#

#USER $user


